# 필요 라이브러리

In [23]:
import pandas as pd

In [24]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz  # 의사결정트리, 시각화

In [25]:
import graphviz  # 시각화

# 데이터 불러오기 및 분리

In [26]:
train_data = pd.read_csv('train.csv')  # 데이터셋 불러오기
train_data = train_data.drop('Id', axis=1) # Id(1열) 제거
train_data

       S1  C1  S2  C2  S3  C3  S4  C4  S5  C5  CLASS
0       2  10   1   4   3  10   1  10   2  11      3
1       4   7   4   4   3  10   1   1   2   3      0
2       2  13   4   7   1  10   1  13   3   4      1
3       2  11   3  11   1   1   2   6   3  10      1
4       3   7   1   9   1   3   3   3   2   9      2
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
25005   3   5   4   2   2   1   3  13   1  13      1
25006   2   2   3  12   2   7   3   1   2   6      0
25007   3   4   2  12   1  10   3  10   1   1      1
25008   3   6   1   8   2   5   2  10   4  11      0
25009   4   7   3   9   4   4   3   1   4   2      0

[25010 rows x 11 columns]

In [27]:
# 학습 값
x = train_data.drop('CLASS', axis=1)  # CLASS(정답) 열 제거
x

       S1  C1  S2  C2  S3  C3  S4  C4  S5  C5
0       2  10   1   4   3  10   1  10   2  11
1       4   7   4   4   3  10   1   1   2   3
2       2  13   4   7   1  10   1  13   3   4
3       2  11   3  11   1   1   2   6   3  10
4       3   7   1   9   1   3   3   3   2   9
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
25005   3   5   4   2   2   1   3  13   1  13
25006   2   2   3  12   2   7   3   1   2   6
25007   3   4   2  12   1  10   3  10   1   1
25008   3   6   1   8   2   5   2  10   4  11
25009   4   7   3   9   4   4   3   1   4   2

[25010 rows x 10 columns]

In [28]:
# trainset 정답
y = train_data['CLASS']
y

0        3
1        0
2        1
3        1
4        2
        ..
25005    1
25006    0
25007    1
25008    0
25009    0
Name: CLASS, Length: 25010, dtype: int64

# 의사결정트리

In [35]:
classifier = DecisionTreeClassifier(random_state=103)

In [36]:
classifier.fit(x, y)

DecisionTreeClassifier(random_state=103)

In [ ]:
dot_data = export_